#Faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada
print('Tabuada')
n1 = int(input('Digite o numero: '))
print('-' * 12)
print(f'{n1} X 0 = {n1 * 0}')
print(f'{n1} X 1 = {n1 * 1}')
print(f'{n1} X 2 = {n1 * 2}')
print(f'{n1} X 3 = {n1 * 3}')
print(f'{n1} X 4 = {n1 * 4}')
print(f'{n1} X 5 = {n1 * 5}')
print(f'{n1} X 6 = {n1 * 6}')
print(f'{n1} X 7 = {n1 * 7}')
print(f'{n1} X 8 = {n1 * 8}')
print(f'{n1} X 9 = {n1 * 9}')
print(f'{n1} X 10 = {n1 * 10}')
print('-' * 12)